module.exports = {
    AUTH_LOGIN : 'AUTH_LOGIN',
    AUTH_LOGIN_SUCCESS : 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_ERROR : 'AUTH_LOGIN_ERROR',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_SUCCESS : 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR : 'REGISTER_USER_ERROR'
}